version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SyncSec!2026}
      POSTGRES_DB: ${POSTGRES_DB:-commucore_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - govflow_net

  backend:
    build: ./backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-SyncSec!2026}@db:5432/${POSTGRES_DB:-commucore_db}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - govflow_net

  docs-service:
    build: ./docs-service
    restart: always
    ports:
      - "8080:8080"
    networks:
      - govflow_net

  realtime-service:
    build: ./realtime-service
    restart: always
    ports:
      - "8081:8081"
    networks:
      - govflow_net

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8000/api/v1
    restart: always
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - govflow_net

volumes:
  postgres_data:

networks:
  govflow_net:
    name: govflow_net
