"""Workflow Engine models

Revision ID: a672d0ee4ba6
Revises: c8ac8e9f69ad
Create Date: 2026-03-04 17:02:55.151922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a672d0ee4ba6'
down_revision: Union[str, Sequence[str], None] = 'c8ac8e9f69ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_templates_id'), 'process_templates', ['id'], unique=False)
    op.create_index(op.f('ix_process_templates_organization_id'), 'process_templates', ['organization_id'], unique=False)
    op.create_table('process_instances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'ARCHIVED', name='processstate'), nullable=False),
    sa.Column('current_step_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('requester_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('management_area_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['management_area_id'], ['management_areas.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['process_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_instances_id'), 'process_instances', ['id'], unique=False)
    op.create_index(op.f('ix_process_instances_organization_id'), 'process_instances', ['organization_id'], unique=False)
    op.create_index(op.f('ix_process_instances_management_area_id'), 'process_instances', ['management_area_id'], unique=False)
    op.create_table('process_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('required_role_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['required_role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['process_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_steps_id'), 'process_steps', ['id'], unique=False)
    op.create_table('approval_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('APPROVE', 'REJECT', 'COMMENT', name='approvalaction'), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['process_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_logs_id'), 'approval_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_logs_id'), table_name='approval_logs')
    op.drop_table('approval_logs')
    op.drop_index(op.f('ix_process_steps_id'), table_name='process_steps')
    op.drop_table('process_steps')
    op.drop_index(op.f('ix_process_instances_organization_id'), table_name='process_instances')
    op.drop_index(op.f('ix_process_instances_id'), table_name='process_instances')
    op.drop_table('process_instances')
    op.drop_index(op.f('ix_process_templates_organization_id'), table_name='process_templates')
    op.drop_index(op.f('ix_process_templates_id'), table_name='process_templates')
    op.drop_table('process_templates')
    # ### end Alembic commands ###
